enum SocketMessageType {
  REFRESH_THEME = 'REFRESH_THEME',
  REFRESH_VOTE = 'REFRESH_VOTE',

  REFRESH = 'REFRESH',
  RESET = 'RESET',
  DATA = 'DATA',

  WRITE_BOARD_START = 'WRITE_BOARD_START',
  WRITE_BOARD_STOP = 'WRITE_BOARD_STOP'
}

export {
  SocketMessageType
}
